import './globals.css'

export const metadata = {
  title: 'Zero2Prod - Newsletter',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" data-theme="cupcake">
      <body>{children}</body>
    </html>
  )
}
