application:
  port: 8000
  host: 127.0.0.1
  base_url: "http://127.0.0.1"
database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
auth:
  authority: https://acr92-dev.eu.auth0.com
email:
  base_url: "http://localhost"
  sender_email: "test@gmail.com"
  authorization_token: "aabbccddeeffgghh"
  timeout_seconds: 10
